# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./persistent_data/mongo/:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=appfall-backend-mongo-1
    volumes:
      - ./persistent_data/backend/:/app/clip/
    ports:
      - "8001:8000"